import type { Metadata } from "next";
import {Rubik} from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-Rubik",
  subsets: ["latin","cyrillic"],
});



export const metadata: Metadata = {
  title: "Галя Балувана",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
