
export const CONFIG = {
  ITEMS_PER_PAGE: 3,
  ITEMS_PER_PAGE_MAIN_PRODUCTS: 4,
  ITEMS_PER_PAGE_MAIN_ARTICLES: 3,
  ITEMS_PER_PAGE_CATEGORY: 6,
  CARD_DISCOUNT_PERCENT: 6,
  FALLBACK_PRICE_RANGE: { min: 0, max: 3000 },
  SITE_URL: "https://deliveryshop.ua",
  TEMPORARY_EMAIL_DOMAIN: "@deliveryshop.ua",
  MAX_ATTEMPTS: 3,
  TIMEOUT_PERIOD: 180,
  DEFAULT_PAGE_SIZE: 5,
};